# Stocks Details (NSE & BSE)
\* updated weekly to account for changes in the list of stocks

In [68]:
# necessary libraries
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import math

In [80]:
# sending a request to the website
base_url = "https://www.screener.in/screens/357649/all-listed-companies/?limit=25"
response = requests.get(base_url)
# initializing a soup object
soup = BeautifulSoup(response.content, 'html.parser')

In [81]:
# getting the number of pages 
n_pages = math.ceil(int(soup.find_all('div', class_='options')[0]
              .find_all('a', class_='ink-900')[-1].text))

In [ ]:
# dictionary to store the stock names tickers and links
stock_dict = {'stock_name': [], 'stock_ticker': [], 'stock_link': []}
for i in n_pages:
    url = base_url + '&page=' + str(i+1)'
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

In [ ]:
stock_elements = soup.find_all('td', class_='text')
for i in stock_elements[1::2]:
    stock_name.append(i.find('a')['href'])

KeyError: 'text'

In [99]:
second

[<td class="text">
 <a href="/company/RELIANCE/consolidated/" target="_blank">Reliance Industr</a>
 </td>,
 <td class="text">
 <a href="/company/TCS/consolidated/" target="_blank">TCS</a>
 </td>,
 <td class="text">
 <a href="/company/HDFCBANK/consolidated/" target="_blank">HDFC Bank</a>
 </td>,
 <td class="text">
 <a href="/company/BHARTIARTL/consolidated/" target="_blank">Bharti Airtel</a>
 </td>,
 <td class="text">
 <a href="/company/ICICIBANK/consolidated/" target="_blank">ICICI Bank</a>
 </td>,
 <td class="text">
 <a href="/company/INFY/consolidated/" target="_blank">Infosys</a>
 </td>,
 <td class="text">
 <a href="/company/SBIN/consolidated/" target="_blank">St Bk of India</a>
 </td>,
 <td class="text">
 <a href="/company/HINDUNILVR/consolidated/" target="_blank">Hind. Unilever</a>
 </td>,
 <td class="text">
 <a href="/company/BAJFINANCE/consolidated/" target="_blank">Bajaj Finance</a>
 </td>,
 <td class="text">
 <a href="/company/ITC/consolidated/" target="_blank">ITC</a>
 </td>,
 <td class="text">
 <a href="/company/LICI/consolidated/" target="_blank">Life Insurance</a>
 </td>,
 <td class="text">
 <a href="/company/HCLTECH/consolidated/" target="_blank">HCL Technologies</a>
 </td>,
 <td class="text">
 <a href="/company/LT/consolidated/" target="_blank">Larsen &amp; Toubro</a>
 </td>,
 <td class="text">
 <a href="/company/SUNPHARMA/consolidated/" target="_blank">Sun Pharma.Inds.</a>
 </td>,
 <td class="text">
 <a href="/company/MARUTI/consolidated/" target="_blank">Maruti Suzuki</a>
 </td>,
 <td class="text">
 <a href="/company/KOTAKBANK/consolidated/" target="_blank">Kotak Mah. Bank</a>
 </td>,
 <td class="text">
 <a href="/company/M&amp;M/consolidated/" target="_blank">M &amp; M</a>
 </td>,
 <td class="text">
 <a href="/company/ULTRACEMCO/consolidated/" target="_blank">UltraTech Cem.</a>
 </td>,
 <td class="text">
 <a href="/company/WIPRO/consolidated/" target="_blank">Wipro</a>
 </td>,
 <td class="text">
 <a href="/company/AXISBANK/consolidated/" target="_blank">Axis Bank</a>
 </td>,
 <td class="text">
 <a href="/company/BAJAJFINSV/consolidated/" target="_blank">Bajaj Finserv</a>
 </td>,
 <td class="text">
 <a href="/company/ONGC/consolidated/" target="_blank">O N G C</a>
 </td>,
 <td class="text">
 <a href="/company/NTPC/consolidated/" target="_blank">NTPC</a>
 </td>,
 <td class="text">
 <a href="/company/TITAN/consolidated/" target="_blank">Titan Company</a>
 </td>,
 <td class="text">
 <a href="/company/ADANIENT/consolidated/" target="_blank">Adani Enterp.</a>
 </td>]

In [74]:
rows = table.find_all('tr')

In [76]:
for row in rows:
    print(row)

<tr>
<th class="text" scope="colgroup">
<a aria-label="Default Sort" class="" href="?limit=100&amp;order=asc">S.No.</a>
</th>
<th class="text" scope="colgroup">
<a aria-label="Sort on Name" class="" href="?limit=100&amp;sort=name&amp;order=desc">Name</a>
</th>
<th data-tooltip="Current Price" scope="colgroup">
<a aria-label="Sort on Current Price" class="" href="?limit=100&amp;sort=current+price&amp;order=desc">
                    CMP
                    <span style="color: hsl(0, 0%, 45%)">Rs.</span>
</a>
</th>
<th data-tooltip="Price to Earning" scope="colgroup">
<a aria-label="Sort on Price to Earning" class="" href="?limit=100&amp;sort=price+to+earning&amp;order=desc">
                    P/E
                    <span style="color: hsl(0, 0%, 45%)"></span>
</a>
</th>
<th data-tooltip="Market Capitalization" scope="colgroup">
<a aria-label="Sort on Market Capitalization" class="desc" href="?limit=100&amp;sort=market+capitalization&amp;order=desc">
                    Mar Cap
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="Dividend yield" scope="colgroup">
<a aria-label="Sort on Dividend yield" class="" href="?limit=100&amp;sort=dividend+yield&amp;order=desc">
                    Div Yld
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Net Profit latest quarter" scope="colgroup">
<a aria-label="Sort on Net Profit latest quarter" class="" href="?limit=100&amp;sort=net+profit+latest+quarter&amp;order=desc">
                    NP Qtr
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="YOY Quarterly profit growth" scope="colgroup">
<a aria-label="Sort on YOY Quarterly profit growth" class="" href="?limit=100&amp;sort=yoy+quarterly+profit+growth&amp;order=desc">
                    Qtr Profit Var
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Sales latest quarter" scope="colgroup">
<a aria-label="Sort on Sales latest quarter" class="" href="?limit=100&amp;sort=sales+latest+quarter&amp;order=desc">
                    Sales Qtr
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="YOY Quarterly sales growth" scope="colgroup">
<a aria-label="Sort on YOY Quarterly sales growth" class="" href="?limit=100&amp;sort=yoy+quarterly+sales+growth&amp;order=desc">
                    Qtr Sales Var
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Return on capital employed" scope="colgroup">
<a aria-label="Sort on Return on capital employed" class="" href="?limit=100&amp;sort=return+on+capital+employed&amp;order=desc">
                    ROCE
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
</tr>
<tr data-row-company-id="2726">
<td class="text">1.</td>
<td class="text">
<a href="/company/RELIANCE/consolidated/" target="_blank">Reliance Industr</a>
</td>
<td>1224.90</td><td>23.96</td><td>1657579.90</td><td>0.41</td><td>21930.00</td><td>7.38</td><td>239986.00</td><td>6.62</td><td>9.61</td>
</tr>
<tr data-row-company-id="3365">
<td class="text">2.</td>
<td class="text">
<a href="/company/TCS/consolidated/" target="_blank">TCS</a>
</td>
<td>3904.50</td><td>28.97</td><td>1412682.27</td><td>1.41</td><td>12444.00</td><td>5.16</td><td>63973.00</td><td>5.60</td><td>64.28</td>
</tr>
<tr data-row-company-id="1298">
<td class="text">3.</td>
<td class="text">
<a href="/company/HDFCBANK/consolidated/" target="_blank">HDFC Bank</a>
</td>
<td>1717.35</td><td>18.88</td><td>1313806.54</td><td>1.14</td><td>18340.11</td><td>2.31</td><td>85040.17</td><td>9.01</td><td>7.67</td>
</tr>
<tr data-row-company-id="467">
<td class="text">4.</td>
<td class="text">
<a href="/company/BHARTIARTL/consolidated/" target="_blank">Bharti Airtel</a>
</td>
<td>1675.55</td><td>50.16</td><td>1002917.45</td><td>0.48</td><td>16134.60</td><td>230.71</td><td>45129.30</td><td>19.08</td><td>13.13</td>
</tr>
<tr data-row-company-id="1384">
<td class="text">5.</td>
<td class="text">
<a href="/company/ICICIBANK/consolidated/" target="_blank">ICICI Bank</a>
</td>
<td>1251.15</td><td>17.96</td><td>883659.31</td><td>0.80</td><td>13846.89</td><td>16.56</td><td>47037.12</td><td>15.10</td><td>7.60</td>
</tr>
<tr data-row-company-id="1489">
<td class="text">6.</td>
<td class="text">
<a href="/company/INFY/consolidated/" target="_blank">Infosys</a>
</td>
<td>1842.30</td><td>27.67</td><td>764973.58</td><td>2.06</td><td>6822.00</td><td>11.46</td><td>41764.00</td><td>7.58</td><td>39.99</td>
</tr>
<tr data-row-company-id="3188">
<td class="text">7.</td>
<td class="text">
<a href="/company/SBIN/consolidated/" target="_blank">St Bk of India</a>
</td>
<td>727.70</td><td>8.19</td><td>649444.60</td><td>1.88</td><td>19483.78</td><td>17.27</td><td>124653.66</td><td>10.44</td><td>6.16</td>
</tr>
<tr data-row-company-id="1350">
<td class="text">8.</td>
<td class="text">
<a href="/company/HINDUNILVR/consolidated/" target="_blank">Hind. Unilever</a>
</td>
<td>2329.40</td><td>52.87</td><td>547313.79</td><td>1.80</td><td>2989.00</td><td>2.93</td><td>15818.00</td><td>1.61</td><td>27.24</td>
</tr>
<tr data-row-company-id="372">
<td class="text">9.</td>
<td class="text">
<a href="/company/BAJFINANCE/consolidated/" target="_blank">Bajaj Finance</a>
</td>
<td>8426.60</td><td>32.68</td><td>522346.94</td><td>0.43</td><td>4308.19</td><td>16.70</td><td>18035.11</td><td>27.33</td><td>11.92</td>
</tr>
<tr data-row-company-id="1552">
<td class="text">10.</td>
<td class="text">
<a href="/company/ITC/consolidated/" target="_blank">ITC</a>
</td>
<td>408.60</td><td>25.73</td><td>511259.91</td><td>3.37</td><td>5013.18</td><td>-8.40</td><td>18790.17</td><td>9.28</td><td>37.47</td>
</tr>
<tr data-row-company-id="1275221">
<td class="text">11.</td>
<td class="text">
<a href="/company/LICI/consolidated/" target="_blank">Life Insurance</a>
</td>
<td>765.15</td><td>11.24</td><td>483957.20</td><td>1.31</td><td>11008.68</td><td>16.69</td><td>203751.32</td><td>-4.81</td><td>72.95</td>
</tr>
<tr data-row-company-id="1297">
<td class="text">12.</td>
<td class="text">
<a href="/company/HCLTECH/consolidated/" target="_blank">HCL Technologies</a>
</td>
<td>1709.90</td><td>27.18</td><td>464009.59</td><td>3.16</td><td>4594.00</td><td>5.54</td><td>29890.00</td><td>5.08</td><td>29.60</td>
</tr>
<tr data-row-company-id="1870">
<td class="text">13.</td>
<td class="text">
<a href="/company/LT/consolidated/" target="_blank">Larsen &amp; Toubro</a>
</td>
<td>3221.85</td><td>31.93</td><td>443060.76</td><td>0.87</td><td>3973.98</td><td>13.96</td><td>64667.78</td><td>17.31</td><td>13.44</td>
</tr>
<tr data-row-company-id="3245">
<td class="text">14.</td>
<td class="text">
<a href="/company/SUNPHARMA/consolidated/" target="_blank">Sun Pharma.Inds.</a>
</td>
<td>1714.20</td><td>34.88</td><td>411294.00</td><td>0.79</td><td>2912.98</td><td>22.66</td><td>13675.46</td><td>10.46</td><td>17.32</td>
</tr>
<tr data-row-company-id="2023">
<td class="text">15.</td>
<td class="text">
<a href="/company/MARUTI/consolidated/" target="_blank">Maruti Suzuki</a>
</td>
<td>12762.90</td><td>27.59</td><td>401268.86</td><td>0.98</td><td>3726.90</td><td>16.22</td><td>38764.30</td><td>15.67</td><td>21.82</td>
</tr>
<tr>
<th class="text" scope="colgroup">
<a aria-label="Default Sort" class="" href="?limit=100&amp;order=asc">S.No.</a>
</th>
<th class="text" scope="colgroup">
<a aria-label="Sort on Name" class="" href="?limit=100&amp;sort=name&amp;order=desc">Name</a>
</th>
<th data-tooltip="Current Price" scope="colgroup">
<a aria-label="Sort on Current Price" class="" href="?limit=100&amp;sort=current+price&amp;order=desc">
                    CMP
                    <span style="color: hsl(0, 0%, 45%)">Rs.</span>
</a>
</th>
<th data-tooltip="Price to Earning" scope="colgroup">
<a aria-label="Sort on Price to Earning" class="" href="?limit=100&amp;sort=price+to+earning&amp;order=desc">
                    P/E
                    <span style="color: hsl(0, 0%, 45%)"></span>
</a>
</th>
<th data-tooltip="Market Capitalization" scope="colgroup">
<a aria-label="Sort on Market Capitalization" class="desc" href="?limit=100&amp;sort=market+capitalization&amp;order=desc">
                    Mar Cap
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="Dividend yield" scope="colgroup">
<a aria-label="Sort on Dividend yield" class="" href="?limit=100&amp;sort=dividend+yield&amp;order=desc">
                    Div Yld
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Net Profit latest quarter" scope="colgroup">
<a aria-label="Sort on Net Profit latest quarter" class="" href="?limit=100&amp;sort=net+profit+latest+quarter&amp;order=desc">
                    NP Qtr
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="YOY Quarterly profit growth" scope="colgroup">
<a aria-label="Sort on YOY Quarterly profit growth" class="" href="?limit=100&amp;sort=yoy+quarterly+profit+growth&amp;order=desc">
                    Qtr Profit Var
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Sales latest quarter" scope="colgroup">
<a aria-label="Sort on Sales latest quarter" class="" href="?limit=100&amp;sort=sales+latest+quarter&amp;order=desc">
                    Sales Qtr
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="YOY Quarterly sales growth" scope="colgroup">
<a aria-label="Sort on YOY Quarterly sales growth" class="" href="?limit=100&amp;sort=yoy+quarterly+sales+growth&amp;order=desc">
                    Qtr Sales Var
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Return on capital employed" scope="colgroup">
<a aria-label="Sort on Return on capital employed" class="" href="?limit=100&amp;sort=return+on+capital+employed&amp;order=desc">
                    ROCE
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
</tr>
<tr data-row-company-id="1818">
<td class="text">16.</td>
<td class="text">
<a href="/company/KOTAKBANK/consolidated/" target="_blank">Kotak Mah. Bank</a>
</td>
<td>1945.30</td><td>19.67</td><td>386762.63</td><td>0.10</td><td>4701.02</td><td>10.23</td><td>16633.14</td><td>14.75</td><td>7.86</td>
</tr>
<tr data-row-company-id="1973">
<td class="text">17.</td>
<td class="text">
<a href="/company/M&amp;M/consolidated/" target="_blank">M &amp; M</a>
</td>
<td>2831.95</td><td>28.43</td><td>352161.15</td><td>0.75</td><td>3624.48</td><td>19.64</td><td>41470.05</td><td>17.48</td><td>13.58</td>
</tr>
<tr data-row-company-id="3525">
<td class="text">18.</td>
<td class="text">
<a href="/company/ULTRACEMCO/consolidated/" target="_blank">UltraTech Cem.</a>
</td>
<td>11490.10</td><td>52.91</td><td>331719.26</td><td>0.61</td><td>1473.51</td><td>-17.20</td><td>17193.33</td><td>2.71</td><td>15.12</td>
</tr>
<tr data-row-company-id="3763">
<td class="text">19.</td>
<td class="text">
<a href="/company/WIPRO/consolidated/" target="_blank">Wipro</a>
</td>
<td>305.35</td><td>25.78</td><td>319728.17</td><td>1.96</td><td>3366.70</td><td>24.48</td><td>22318.80</td><td>0.51</td><td>16.93</td>
</tr>
<tr data-row-company-id="348">
<td class="text">20.</td>
<td class="text">
<a href="/company/AXISBANK/consolidated/" target="_blank">Axis Bank</a>
</td>
<td>992.95</td><td>10.91</td><td>307418.64</td><td>0.10</td><td>6778.91</td><td>3.86</td><td>32162.20</td><td>11.42</td><td>7.06</td>
</tr>
<tr data-row-company-id="373">
<td class="text">21.</td>
<td class="text">
<a href="/company/BAJAJFINSV/consolidated/" target="_blank">Bajaj Finserv</a>
</td>
<td>1894.85</td><td>35.29</td><td>302543.52</td><td>0.05</td><td>4411.89</td><td>3.40</td><td>32041.81</td><td>10.34</td><td>11.72</td>
</tr>
<tr data-row-company-id="2320">
<td class="text">22.</td>
<td class="text">
<a href="/company/ONGC/consolidated/" target="_blank">O N G C</a>
</td>
<td>233.65</td><td>7.43</td><td>293938.22</td><td>5.24</td><td>9783.64</td><td>-17.97</td><td>166096.68</td><td>-0.75</td><td>18.43</td>
</tr>
<tr data-row-company-id="2303">
<td class="text">23.</td>
<td class="text">
<a href="/company/NTPC/consolidated/" target="_blank">NTPC</a>
</td>
<td>302.35</td><td>13.34</td><td>293178.70</td><td>2.56</td><td>5169.69</td><td>-1.80</td><td>45052.82</td><td>5.21</td><td>10.47</td>
</tr>
<tr data-row-company-id="3437">
<td class="text">24.</td>
<td class="text">
<a href="/company/TITAN/consolidated/" target="_blank">Titan Company</a>
</td>
<td>3233.20</td><td>88.67</td><td>287039.02</td><td>0.34</td><td>1047.00</td><td>-0.57</td><td>17740.00</td><td>25.25</td><td>22.70</td>
</tr>
<tr data-row-company-id="56">
<td class="text">25.</td>
<td class="text">
<a href="/company/ADANIENT/consolidated/" target="_blank">Adani Enterp.</a>
</td>
<td>2223.70</td><td>67.27</td><td>256655.17</td><td>0.06</td><td>228.64</td><td>-96.89</td><td>22848.42</td><td>-8.79</td><td>9.87</td>
</tr>